### PR TITLE
support JRuby

### PR DESCRIPTION
**Pull request by jfeltesse-mdsol**
~~WIP - opening PR to see if the travis settings are correct~~

Looks like it's passing, should be good to go then?

@JordiPolo @ssteeg-mdsol @cabbott @ykitamura-mdsol

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
P.S. I'm not so familiar with rubygems.org but it seems from now you'll need to build using both MRI and JRuby to produce 
```
lorekeeper-x.y.z-java.gem
lorekeeper-x.y.z.gem
```

**Comment by jfeltesse-mdsol** [comment]
adhoc'ing now, will post results / amend in a few.

**Comment by jfeltesse-mdsol** [comment]
So it seems that the "platform: 'java'" bit in the gemspec makes the gem name become "lorekeeper java" which is ok on its own but the problem is that when it's used as a dependency in another gem it fails to find it.
Removing the offending part works but I need a bit more time to confirm it's not going to have a surprising behavior, e.g. http://blog.mattwynne.net/2011/04/26/targeting-multiple-platforms-jruby-etc-with-a-rubygems-gemspec/

**Comment by ykitamura-mdsol** [comment]
sorry for the late review
looks good to me 👍

**Comment by jfeltesse-mdsol** [comment]
Closing for now until we have time to actually tackle this seriously and understand better why gems depending on lorekeeper need to be `-java` too (which shouldn't be)

**Pull request closed without merging**
